'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class estimate_payment_byContract

    '''<summary>
    '''txtContractNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvOneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOneTime As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvPaymentFlex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPaymentFlex As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvPaymentFix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPaymentFix As Global.System.Web.UI.WebControls.GridView
End Class
