
	<!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="../index.aspx">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Home</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>แจ้งงาน</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Jobs:</h6>
          <a class="dropdown-item" href="../jobs/jobs.aspx">เปิด Job</a>
          <a class="dropdown-item" href="../jobs/jobslist.aspx">แสดงรายการ Job</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Setting:</h6>
          <a class="dropdown-item" href="#">ประเภท Job</a>
          <a class="dropdown-item" href="#">Blank Page</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>จัดการทรัพย์สิน</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Assets:</h6>
          <a class="dropdown-item" href="../assets/Assets.aspx">จัดการทรัพย์สิน</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Setting:</h6>
          <a class="dropdown-item" href="#">ประเภท ทรัพย์สิน</a>
          <a class="dropdown-item" href="#">Blank Page</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Admin</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
			<h6 class="dropdown-header">Admin:</h6>
			<a class="dropdown-item" href="#">Users</a>
			<div class="dropdown-divider"></div>
			<h6 class="dropdown-header">Setting:</h6>
			<a class="dropdown-item" href="#">Branch</a>
			<a class="dropdown-item" href="#">Department</a>
			<a class="dropdown-item" href="#">Section</a>
			<a class="dropdown-item" href="#">Position</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
    </ul>
    <!-- end Sidebar -->
